In [57]:
class Point:
    def show(self,a,b):
        
        print('({0},{1})'.format(a,b))
        return a+b
    
a.Point(1,2)
a.show()

b=Point(3,4)
b=show()

a=a+b
a.show()

AttributeError: 'numpy.ndarray' object has no attribute 'Point'

In [52]:
import csv


f=open('seoul.csv','r',encoding='cp949')
data=csv.reader(f)
header=next(data)

weeks=[1,8,15,22,29]
weekf=[7,14,21,28,31]

i=0
temp=[0,0,0,0,0]

for row in data:
    temperature=0
    row[4]=float(row[4])
    row[3]=float(row[3])
    temperature=float(row[4]-row[3])
    temp[i]=temp[i]+temperature

    k=int(row[0].split('-')[2])%7
    
    if k==0 or int(row[0].split('-')[2])==31:
        i=i+1


    
for i in range(4):
    temp[i]=temp[i]/7
temp[4]=temp[4]/3

max_num=0
max_w=temp[0]
for i in range(5):
    if temp[i]>max_w:
        max_w=temp[i]
        max_num=i

print('Max Week=5/{0}~5/{1}'.format(weeks[max_num],weekf[max_num]))
        

1
[9.185714285714285, 11.385714285714284, 7.185714285714285, 8.557142857142857, 9.700000000000001]
Max Week=5/8~5/14


In [68]:
import numpy as np
import matplotlib.pyplot as plt

a=np.array([1,1,0,1,0,1,1,1,1,0,1,0,1,1,0,1,0,0])
a=a.reshape(3,6)
q=[1,1,0,0,1,0]

print(a[0])
cos=np.array([0,0,0])

for k in range(3):
    for i in a[0]:
        cos[k]=cos[k]+i*i
    cos[k]=np.sqrt((cos[k]))

u=np.array([0,0,0])
for i in range(3):
    u[i]=a[i]*q
coss=np.array([0,0,0])
for i in ragne(3):
    coss=u[i]/cos[i]
    
x=[1,2,3]
y=[coss[0], coss[1],coss[2]]
plt.hist(y, color='b')

[1 1 0 1 0 1]
[2 2 2]
[1 1 0 0 1 0]
[1 1 0 0 0 0]
